### ISSUE TITLE
ImportError: No module named 'cmd_exception'

### ISSUE THREAD

**Issue by fernandocanizo** [graze/pycmd-utils#1]
Hello, I'm getting this error after a:

$ git clone https://github.com/graze/pycmd-utils.git
$ cd pycmd-utils
$ sudo python setup.py install
$ python

> > > import cmd_utils
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib/python3.4/site-packages/cmd_utils/**init**.py", line 11, in <module>
> > >     from .cmd_utils import run_cmd, run_cmd_list, run_ssh_cmd, run_ssh_cmd_list
> > >   File "/usr/lib/python3.4/site-packages/cmd_utils/cmd_utils.py", line 10, in <module>
> > >     from cmd_exception import ReturnCodeError
> > > ImportError: No module named 'cmd_exception'

**Comment by markeganfuller** [comment]
This code is compatible with Python 2 only, I'd suggest using `subprocess.check_call` from the std library as it's a good replacement for the main (now obsolete) feature of this library.

If you're looking for streaming output wrapping `subprocess.Popen` in a generator should work (as done here https://github.com/graze/pycmd-utils/blob/master/cmd_utils/streaming.py#L33).
